%YAML:1.0
ar_map_boards:
   - { name:"/board1", type:"floating" }
   - { name:"/board2", type:"floating" }
   - { name:"/board3", type:"floating" }
   - { name:"/board4", type:"floating" }
   - { name:"/board5", type:"floating" }
   - { name:"/board6", type:"floating" }
ar_map_cameras:
   - { name:"/camera1", type:"floating" }
   - { name:"/robot_map_camera", type:"fixed", pose:[ [ 0, 0, 0 ], [ 0, 0, 0 ] ] }
